<?php

use Drupal\Core\Language\LanguageInterface;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function hreflang_page_attachments(array &$page) {
  // No need to add hreflang tags for 404/403 pages.
  if (\Drupal::request()->attributes->get('exception')) {
    return;
  }
  $language_manager = \Drupal::getContainer()->get('language_manager');
  $route = drupal_is_front_page() ? '<front>' : '<current>';
  $links = $language_manager->getLanguageSwitchLinks(LanguageInterface::TYPE_INTERFACE, Url::fromRoute($route));
  if (empty($links->links)) {
    return;
  }
  foreach ($links->links as $langcode => $link) {
    $link['url']->setAbsolute();
    $link['url']->setOption('language', $link['language']);
    $link['url']->setOption('query', \Drupal::request()->query->all());
    $page['#attached']['html_head_link'][] = array(array(
      'rel' => 'alternate',
      'hreflang' => $langcode,
      'href' => $link['url']->toString(),
    ));
  }
}
